baseURL = 'https://niu.fm'
languageCode = 'zh-cn'
title = '小牛快跑'
paginate = 3
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "架构，生活"

#   [params.comments]
#     githubRepo = 'canhtran/maverick'
#     theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "关于"
    name = "关于"
    url = "/about/"
    weight = "-110"
  [[menu.main]]
    identifier = "posts"
    name = "认知"
    url = "/posts/"
    weight = -200

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]

